/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myshopinventory;

/**
 *
 * @author Karthikeyan
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblTotalRate = new javax.swing.JLabel();
        txtTotalRate = new javax.swing.JTextField();
        lblRate = new javax.swing.JLabel();
        txtCount = new javax.swing.JTextField();
        lblRate1 = new javax.swing.JLabel();
        cbAvailableRate = new javax.swing.JComboBox<>();
        lblQuantity = new javax.swing.JLabel();
        cbAvailableQuantity = new javax.swing.JComboBox<>();
        lblBrandName = new javax.swing.JLabel();
        cbAvailableBrand = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblRegistration = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(642, 150));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Add");
        jPanel4.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 85, 20));

        btnRemove.setText("Remove");
        jPanel4.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 85, 20));

        btnClose.setText("Close");
        jPanel4.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 85, 20));

        lblTotalRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalRate.setText("Total (in Rs):");
        jPanel4.add(lblTotalRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 80, -1));
        jPanel4.add(txtTotalRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 180, -1));

        lblRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRate.setText("Count:");
        jPanel4.add(lblRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 80, -1));
        jPanel4.add(txtCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 180, -1));

        lblRate1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRate1.setText("Rate (in Rs):");
        jPanel4.add(lblRate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 90, 80, -1));

        cbAvailableRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cbAvailableRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, -1));

        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQuantity.setText("Quantity (in ml):");
        jPanel4.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 60, 80, -1));

        cbAvailableQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cbAvailableQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, -1));

        lblBrandName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBrandName.setText("Brand Name:");
        jPanel4.add(lblBrandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 30, 80, -1));

        cbAvailableBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cbAvailableBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 180, -1));

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(100, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistration.setBackground(new java.awt.Color(0, 0, 255));
        lblRegistration.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblRegistration.setForeground(new java.awt.Color(204, 0, 0));
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setText("Dashboard");
        jPanel2.add(lblRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 40));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Reports");

        jMenu2.setText("Report by time");

        jMenuItem3.setText("Daily Report");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Weekly Report");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Monthly Report");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Quarterly Report");
        jMenu2.add(jMenuItem6);

        jMenu1.add(jMenu2);

        jMenuItem7.setText("Report by Shops");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbAvailableBrand;
    private javax.swing.JComboBox<String> cbAvailableQuantity;
    private javax.swing.JComboBox<String> cbAvailableRate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblRate1;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblTotalRate;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtTotalRate;
    // End of variables declaration//GEN-END:variables
}
